language: node_js
sudo: false
node_js: '9'
addons:
  firefox: latest
  chrome: stable
cache:
  directories:
  - node_modules
before_script:
  - npm install -g polymer-cli
  - npm run lint
branches:
  only:
  - master
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: ./build/default/